### ISSUE TITLE
compile error in ue5.4.3

### ISSUE THREAD

**Issue by DezarM** [immutable/unreal-immutable-sdk#139] opened 2024-10-07 17:09 UTC
when i try build linux version

`

UATHelper: Packaging (Linux): In file included from G:/Uzuron/Plugins/unreal-immutable-sdk/Source/Immutable/Private/Immutable/Actions/ImtblBlueprintAsyncAction.cpp:1:
UATHelper: Packaging (Linux): In file included from G:\Uzuron\Intermediate\Build\Linux\x64\UzuronServer\Development\Engine\SharedPCH.Engine.Project.ValApi.Cpp20.h:3:
UATHelper: Packaging (Linux): In file included from H:\UES-543\Engine\Source\Runtime\Engine\Public\EngineSharedPCH.h:143:
UATHelper: Packaging (Linux): H:\UES-543\Engine\Source\Runtime\Engine\Classes\Engine\GameInstance.h(464,60): error: incomplete type 'UImmutableSubsystem' named in nested name specifier
UATHelper: Packaging (Linux):                 return SubsystemCollection.GetSubsystem<TSubsystemClass>(TSubsystemClass::StaticClass());
UATHelper: Packaging (Linux):                                                                          ^~~~~~~~~~~~~~~~~
UATHelper: Packaging (Linux): G:\Uzuron\Plugins\unreal-immutable-sdk\Source\Immutable\Private\Immutable\Actions\ImtblBlueprintAsyncAction.cpp(11,60): note: in instantiation of function template specialization 'UGameInstance::GetSubsystem<UImmutableSubsystem>' requested here
UATHelper: Packaging (Linux):         return WorldContextObject->GetWorld()->GetGameInstance()->GetSubsystem<UImmutableSubsystem>();
UATHelper: Packaging (Linux):                                                                   ^
UATHelper: Packaging (Linux): G:\Uzuron\Plugins\unreal-immutable-sdk\Source\Immutable\Public\Immutable\Actions\ImtblBlueprintAsyncAction.h(23,8): note: forward declaration of 'UImmutableSubsystem'
UATHelper: Packaging (Linux):         class UImmutableSubsystem* GetSubsystem() const;
UATHelper: Packaging (Linux):               ^
UATHelper: Packaging (Linux): In file included from G:/Uzuron/Plugins/unreal-immutable-sdk/Source/Immutable/Private/Immutable/Actions/ImtblBlueprintAsyncAction.cpp:1:
UATHelper: Packaging (Linux): In file included from G:\Uzuron\Intermediate\Build\Linux\x64\UzuronServer\Development\Engine\SharedPCH.Engine.Project.ValApi.Cpp20.h:3:
UATHelper: Packaging (Linux): In file included from H:\UES-543\Engine\Source\Runtime\Engine\Public\EngineSharedPCH.h:143:
UATHelper: Packaging (Linux): H:\UES-543\Engine\Source\Runtime\Engine\Classes\Engine\GameInstance.h(464,75): error: incomplete definition of type 'UImmutableSubsystem'
UATHelper: Packaging (Linux):                 return SubsystemCollection.GetSubsystem<TSubsystemClass>(TSubsystemClass::StaticClass());
UATHelper: Packaging (Linux):                                                                          ~~~~~~~~~~~~~~~^~
UATHelper: Packaging (Linux): 2 errors generated.
PackagingResults: Error: incomplete type 'UImmutableSubsystem' named in nested name specifier
PackagingResults: Error: incomplete definition of type 'UImmutableSubsystem'
UATHelper: Packaging (Linux): Error executing H:\v22_clang-16.0.6-centos7\x86_64-unknown-linux-gnu\bin\clang++.exe (tool returned code: 1)
UATHelper: Packaging (Linux): [3/37] Compile ImmutableSaveGame.cpp (0:02.79 at +0:39)
UATHelper: Packaging (Linux): [4/37] Compile ImtblLogging.cpp (0:02.75 at +0:39)
UATHelper: Packaging (Linux): [5/37] Compile ImmutableUtilities.cpp (0:03.34 at +0:39)
UATHelper: Packaging (Linux): [6/37] Compile ImmutableBlueprintLibrary.cpp (0:03.45 at +0:39)
`

**Comment by DezarM** [comment] 2024-10-07 17:34
UATHelper: Packaging (Windows): BootstrapPackagedGame: Using Visual Studio 2022 14.34.31948 toolchain (C:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.34.31933) and Windows 10.0.19041.0 SDK (C:\Program Files (x86)\Windows Kits\10).
UATHelper: Packaging (Windows): Determining max actions to execute in parallel (16 physical cores, 32 logical cores)
UATHelper: Packaging (Windows):   Executing up to 16 processes, one per physical core
UATHelper: Packaging (Windows): Using Parallel executor to run 3 action(s)
UATHelper: Packaging (Windows): ------ Building 3 action(s) started ------
UATHelper: Packaging (Windows): ** For Uzuron-Win64-Shipping **
UATHelper: Packaging (Windows): [1/3] Compile [x64] ImtblBlueprintAsyncAction.cpp
UATHelper: Packaging (Windows): H:\UES-543\Engine\Source\Runtime\Engine\Classes\Engine\GameInstance.h(464): error C2027: �ᯮ�짮����� ����।�������� ⨯� "UImmutableSubsystem"
UATHelper: Packaging (Windows): G:\Uzuron\Plugins\unreal-immutable-sdk\Source\Immutable\Public\Immutable\Actions\ImtblBlueprintAsyncAction.h(23): note:  �. ������� "UImmutableSubsystem"
UATHelper: Packaging (Windows): G:\Uzuron\Plugins\unreal-immutable-sdk\Source\Immutable\Private\Immutable\Actions\ImtblBlueprintAsyncAction.cpp(11): note: �믮������ ��������� ��뫪� �� ��������� 蠡��� �㭪樨 "TSubsystemClass *UGameInstance::GetSubsystem<UImmutableSubsystem>(void) const"
UATHelper: Packaging (Windows):         with
UATHelper: Packaging (Windows):         [
UATHelper: Packaging (Windows):             TSubsystemClass=UImmutableSubsystem
UATHelper: Packaging (Windows):         ]
UATHelper: Packaging (Windows): Total time in Parallel executor: 6.76 seconds
UATHelper: Packaging (Windows): Total execution time: 11.19 seconds
UATHelper: Packaging (Windows): Took 11,29s to run dotnet.exe, ExitCode=6
UATHelper: Packaging (Windows): UnrealBuildTool failed. See log for more details. (H:\UES-543\Engine\Programs\AutomationTool\Saved\Logs\UBA-UnrealPak-Win64-Development.txt)
UATHelper: Packaging (Windows): AutomationTool executed for 0h 0m 13s
UATHelper: Packaging (Windows): AutomationTool exiting with ExitCode=6 (6)

**Comment by ImmutableJeffrey** [comment] 2024-10-08 23:02
Could you please provide additional details:
* Commit hash
* Log with readable characters (if possible)

**Comment by ImmutableJeffrey** [comment] 2024-10-29 21:32
Closing, as I could not reproduce the issue on my end and also due to lack of information
If you are still experiencing the same of similar issue, please do not hesitate to reach out
Thanks

**Closed by ImmutableJeffrey** 2024-10-29 21:32 UTC
